# Book settings
project:
  type: book
  output-dir: docs

book:
  title: "R  cookbook"
  author: "Nina Dombrowski"
  #date: "`r Sys.Date()`"
  chapters:
    - index.qmd
    - code/1_intro.qmd
    - code/data_types.qmd
    - code/data_transformations.qmd
    - code/control_structures.qmd
    - code/stats.qmd
    - code/plotting_basics.qmd
    - code/parsing_output_from_annotations.qmd
    - code/2_misc.qmd

logo: 
  small: images/tree_of_life.png

bibliography: references.bib

format:
  html:
    theme: cosmo
    code-overflow: wrap
    embed-resources: true
  # pdf:
  #   documentclass: scrreprt
  #   geometry:
  #     - top=4mm
  #     - left=4mm
  #   #  - textwidth=4.5in
  #     - heightrounded
  #   fontfamily: libertinus
  #   highlight-style: github
  #   pandoc_args: --listings
  #   includes:
  #     in_header: preamble.tex
  #   colorlinks: true
  #   #code-block-bg: 7FB3D5

execute:
  eval: false
  freeze: auto

#knitr:
#  opts_chunk:
#    collapse: true

df-print: paged
